### ISSUE TITLE
can't use "name" attribute

### ISSUE THREAD

**Issue by vv-ivanov** [antonreshetov/vue-form-components#11]
hi, I added
`<vue-input v-model="formCarrier.email" name="mail" style="width: 100%" placeholder="somemail@domain.com"></vue-input>`

but it doesn't work after rendering.

other attributes like a "readonly, type, placeholder" still work

**Comment by antonreshetov** [comment]
Hi @yakudza73 
Can you please more fully. What did you expect and what did you get.

**Comment by antonreshetov** [comment]
Should be fixed in f2dce4f23063a697276e17957d55d97729aac21a

**Comment by yakudza73** [comment]
I checked. it's still doesn't work with checkbox, in other components everything is ok

**Comment by vv-ivanov** [comment]
> Should be fixed in [f2dce4f](https://github.com/antonreshetov/vue-form-components/commit/f2dce4f23063a697276e17957d55d97729aac21a)

I checked. it's still doesn't work with checkbox, in other components everything is ok

**Comment by antonreshetov** [comment]
Should be fixed now in 76a4eb6e7d0a5bbd6380165d15d95110d2ac13db

**Comment by vv-ivanov** [comment]
> Should be fixed now in [76a4eb6](https://github.com/antonreshetov/vue-form-components/commit/76a4eb6e7d0a5bbd6380165d15d95110d2ac13db)

Thanks, now everything is all right
